//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSTracka.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPSTracka.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string Altitude {
            get {
                return ResourceManager.GetString("Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm port.
        /// </summary>
        internal static string COMPort {
            get {
                return ResourceManager.GetString("COMPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit?
        ///GPS Logging will stop..
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue in current file {0}?.
        /// </summary>
        internal static string ContinueInCurrentFile {
            get {
                return ResourceManager.GetString("ContinueInCurrentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format test.
        /// </summary>
        internal static string DateFormatTest {
            get {
                return ResourceManager.GetString("DateFormatTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date = {0}
        ///Value = {1}.
        /// </summary>
        internal static string DateTestMessage {
            get {
                return ResourceManager.GetString("DateTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date + Time.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a proper file path.
        /// </summary>
        internal static string err_BadPath {
            get {
                return ResourceManager.GetString("err_BadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create the directory specified.  Try another location..
        /// </summary>
        internal static string err_CreateDir {
            get {
                return ResourceManager.GetString("err_CreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV text qualifier cannot be empty..
        /// </summary>
        internal static string err_CSVQualifierEmpty {
            get {
                return ResourceManager.GetString("err_CSVQualifierEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV separator cannot be empty..
        /// </summary>
        internal static string err_CSVSeparatorEmpty {
            get {
                return ResourceManager.GetString("err_CSVSeparatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string err_ERROR {
            get {
                return ResourceManager.GetString("err_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string err_ErrorTitle {
            get {
                return ResourceManager.GetString("err_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string err_ErrorTitleMsg {
            get {
                return ResourceManager.GetString("err_ErrorTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help file {0} is not availbale.
        ///{1}.
        /// </summary>
        internal static string err_HelpNotAvailable {
            get {
                return ResourceManager.GetString("err_HelpNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of date in CSV file is invalid:.
        /// </summary>
        internal static string err_InvalidCSVDateFormat {
            get {
                return ResourceManager.GetString("err_InvalidCSVDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format is invalid..
        /// </summary>
        internal static string err_InvalidFormat {
            get {
                return ResourceManager.GetString("err_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, the format string is invalid.
        ///.
        /// </summary>
        internal static string err_InvalidFormatString {
            get {
                return ResourceManager.GetString("err_InvalidFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given format for KML point description is invalid.
        /// </summary>
        internal static string err_InvalidKmlPointDescFormat {
            get {
                return ResourceManager.GetString("err_InvalidKmlPointDescFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given format for KML point name is invalid.
        /// </summary>
        internal static string err_InvalidKmlPointNameFormat {
            get {
                return ResourceManager.GetString("err_InvalidKmlPointNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given log format is invalid.
        /// </summary>
        internal static string err_InvalidLogFormat {
            get {
                return ResourceManager.GetString("err_InvalidLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create directory for NMEA file {0}: {1}.
        /// </summary>
        internal static string err_NmeaCreateDir {
            get {
                return ResourceManager.GetString("err_NmeaCreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open NMEA file {0}: {1}.
        /// </summary>
        internal static string err_NmeaOpenFile {
            get {
                return ResourceManager.GetString("err_NmeaOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one CSV field..
        /// </summary>
        internal static string err_NoCSVFields {
            get {
                return ResourceManager.GetString("err_NoCSVFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path must be rooted.
        /// </summary>
        internal static string err_PathMustBeRooted {
            get {
                return ResourceManager.GetString("err_PathMustBeRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position part is null..
        /// </summary>
        internal static string err_PositionIsNull {
            get {
                return ResourceManager.GetString("err_PositionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Failed to set power policy for unattended mode. This may cause device to fall asleep and stop recording your track..
        /// </summary>
        internal static string err_PowerPolicyNotifiyFailed {
            get {
                return ResourceManager.GetString("err_PowerPolicyNotifiyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder, please..
        /// </summary>
        internal static string err_SelectFolderPlease {
            get {
                return ResourceManager.GetString("err_SelectFolderPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t write location to file. Try changing locations..
        /// </summary>
        internal static string err_WriteToFile {
            get {
                return ResourceManager.GetString("err_WriteToFile", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ErrorIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exaple of formatting.
        /// </summary>
        internal static string ExapleOfFormatting {
            get {
                return ResourceManager.GetString("ExapleOfFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:yyyy-MM-ddTHH:mm:ssZ}.
        /// </summary>
        internal static string format_KmlDescDefault {
            get {
                return ResourceManager.GetString("format_KmlDescDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4:H:mm:ss} {1},{2}, {3}.
        /// </summary>
        internal static string format_TextLogDefault {
            get {
                return ResourceManager.GetString("format_TextLogDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC now={0}, lon={1}, lat={2}, alt={3}, now={4}, el.unit={5}
        ///The result is:
        ///.
        /// </summary>
        internal static string FormatTestInfo {
            get {
                return ResourceManager.GetString("FormatTestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSTracka Version.
        /// </summary>
        internal static string GPSTrackaVersion {
            get {
                return ResourceManager.GetString("GPSTrackaVersion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon InfoIcon {
            get {
                object obj = ResourceManager.GetObject("InfoIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line color.
        /// </summary>
        internal static string LineColor {
            get {
                return ResourceManager.GetString("LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging options.
        /// </summary>
        internal static string LoggingOptions {
            get {
                return ResourceManager.GetString("LoggingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order change in language to take effect, you must restart GPSTracka..
        /// </summary>
        internal static string msg_LngChange {
            get {
                return ResourceManager.GetString("msg_LngChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening....
        /// </summary>
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait ....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points too near {0:0}m.
        /// </summary>
        internal static string PointsTooNear {
            get {
                return ResourceManager.GetString("PointsTooNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling rate.
        /// </summary>
        internal static string PollingRate {
            get {
                return ResourceManager.GetString("PollingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start.
        /// </summary>
        internal static string PressStart {
            get {
                return ResourceManager.GetString("PressStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended:.
        /// </summary>
        internal static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running....
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat. open.
        /// </summary>
        internal static string Satellite_Started {
            get {
                return ResourceManager.GetString("Satellite_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat. closed.
        /// </summary>
        internal static string Satellite_Stopped {
            get {
                return ResourceManager.GetString("Satellite_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting ....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inv. pos. {0}.
        /// </summary>
        internal static string status_InvalidPos {
            get {
                return ResourceManager.GetString("status_InvalidPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inv. pos. {0} - wait.
        /// </summary>
        internal static string status_InvalidPosWait {
            get {
                return ResourceManager.GetString("status_InvalidPosWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opening....
        /// </summary>
        internal static string status_Opening {
            get {
                return ResourceManager.GetString("status_Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position received.
        /// </summary>
        internal static string status_PositionReceived {
            get {
                return ResourceManager.GetString("status_PositionReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to running....
        /// </summary>
        internal static string status_Running {
            get {
                return ResourceManager.GetString("status_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS stopped.
        /// </summary>
        internal static string Status_Stopped {
            get {
                return ResourceManager.GetString("Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped.
        /// </summary>
        internal static string Status_Stopped_simple {
            get {
                return ResourceManager.GetString("Status_Stopped_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS stopping.
        /// </summary>
        internal static string Status_Stopping {
            get {
                return ResourceManager.GetString("Status_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped..
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current track is saved..
        /// </summary>
        internal static string TrackSaved {
            get {
                return ResourceManager.GetString("TrackSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will begin to read GPS data after {0} seconds..
        /// </summary>
        internal static string WillBeginReading {
            get {
                return ResourceManager.GetString("WillBeginReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0km/h.
        /// </summary>
        internal static string ZeroKmH {
            get {
                return ResourceManager.GetString("ZeroKmH", resourceCulture);
            }
        }
    }
}
